"""Каталог проверок аудита (используется UI, документацией и тестами)."""
from __future__ import annotations

CHECKS: list[dict] = [
    # ---- Вёрстка
    {"code": "out_of_bounds", "title": "Элемент вышел за границы слайда", "category": "layout", "deterministic": True,
     "how": "Габариты фигуры сравниваются с размером слайда (допуск 0,4%)."},
    {"code": "overlap", "title": "Два блока наложились друг на друга", "category": "layout", "deterministic": True,
     "how": "Пересечение прямоугольников > 3% меньшей площади, кроме вложения в контейнер-подложку."},
    {"code": "text_overflow", "title": "Текст не поместился в свою рамку", "category": "layout", "deterministic": True,
     "how": "Высота текста считается по реальным метрикам шрифта (PIL/FreeType) и сравнивается с рамкой."},
    {"code": "text_cut", "title": "Текст обрезан краем слайда", "category": "layout", "deterministic": True,
     "how": "Текстовая рамка выходит за пределы слайда."},
    {"code": "alignment", "title": "Блоки не выровнены по направляющим", "category": "layout", "deterministic": True,
     "how": "Карточки ряда на одной высоте; левый край контента совпадает с направляющей макета."},
    {"code": "margins", "title": "Контент заходит в поля у краёв", "category": "layout", "deterministic": True,
     "how": "Контент не выходит за контентную область холста (поля и зона колонтитула шаблона)."},
    {"code": "image_stretched", "title": "Картинка растянута, пропорции нарушены", "category": "layout", "deterministic": True,
     "how": "Соотношение сторон исходного изображения с учётом обрезки равно соотношению рамки (допуск 3%)."},
    # ---- Шаблон
    {"code": "font_not_in_template", "title": "Шрифт не из шаблона", "category": "template", "deterministic": True,
     "how": "Гарнитура каждого абзаца есть в типографике шаблона."},
    {"code": "font_families", "title": "Гарнитур больше двух", "category": "template", "deterministic": True,
     "how": "Не более двух гарнитур на слайде."},
    {"code": "size_not_in_scale", "title": "Кегль не из типографической шкалы", "category": "template", "deterministic": True,
     "how": "Кегль входит в шкалу, извлечённую из шаблона (допуск 0,25 pt)."},
    {"code": "color_not_in_palette", "title": "Цвет не из палитры шаблона", "category": "template", "deterministic": True,
     "how": "Цвет совпадает с токеном палитры или его оттенком (смесь с фоном/белым/чёрным)."},
    {"code": "layout_not_from_template", "title": "Слайд собран не на макете шаблона", "category": "template", "deterministic": True,
     "how": "Макет слайда присутствует среди макетов исходного шаблона."},
    {"code": "chrome_moved", "title": "Логотип или колонтитул сдвинут", "category": "template", "deterministic": True,
     "how": "Элементы-«хром» шаблона стоят на исходных координатах."},
    {"code": "contrast", "title": "Контраст текста к фону ниже 4,5:1", "category": "template", "deterministic": True,
     "how": "WCAG 2.1 по пикселям рендера под текстом; крупный текст (≥18 pt или ≥14 pt полужирный) — 3:1."},
    # ---- Плотность
    {"code": "too_many_bullets", "title": "Больше 6 буллетов на слайде", "category": "density", "deterministic": True,
     "how": "Считаются маркированные абзацы и заголовки пунктов."},
    {"code": "long_bullet", "title": "Буллет длиннее 15 слов", "category": "density", "deterministic": True,
     "how": "Подсчёт слов в каждом пункте."},
    {"code": "table_size", "title": "Таблица больше 7 строк или 5 колонок", "category": "density", "deterministic": True,
     "how": "Размер нативной таблицы."},
    {"code": "chart_series", "title": "Больше 5 серий на диаграмме", "category": "density", "deterministic": True,
     "how": "Число c:ser в части диаграммы."},
    {"code": "fill_ratio", "title": "Слайд заполнен меньше ¼ или больше ¾", "category": "density", "deterministic": True,
     "how": "Площадь объединения объектов относительно площади слайда."},
    # ---- Целостность
    {"code": "file_open", "title": "Файл не открывается", "category": "integrity", "deterministic": True,
     "how": "Файл открывается python-pptx, LibreOffice рендерит все страницы."},
    {"code": "placeholder_text", "title": "Остался текст-заглушка", "category": "integrity", "deterministic": True,
     "how": "Регулярные выражения: lorem ipsum, XXX, TODO, «вставьте текст», «Имя Фамилия», «Вывод 1»…"},
    {"code": "empty_slide", "title": "Пустой слайд или слайд с одним заголовком", "category": "integrity", "deterministic": True,
     "how": "На контентном слайде нет объектов, кроме заголовка."},
    {"code": "raster_slide", "title": "Слайд оказался картинкой", "category": "integrity", "deterministic": True,
     "how": "Одна картинка ≥90% площади и ни одного текстового объекта."},
    {"code": "chart_labels", "title": "У диаграммы нет подписей осей, единиц или легенды", "category": "integrity", "deterministic": True,
     "how": "Разбор XML диаграммы: подписи значений, заголовок оси, легенда для нескольких серий."},
    {"code": "duplicate_slides", "title": "Два слайда дублируют друг друга", "category": "integrity", "deterministic": True,
     "how": "Мера Жаккара по словам текстов слайдов > 0,8."},
    {"code": "language", "title": "Колода не на одном языке", "category": "content", "deterministic": True,
     "how": "Доля латиницы среди букв слайда > 30%."},
    # ---- Контекстные (VLM)
    {"code": "title_conclusion", "title": "Заголовок содержит вывод, а не тему", "category": "content", "deterministic": False, "how": "VLM по картинке слайда (вопрос 1)."},
    {"code": "content_matches_title", "title": "Содержимое соответствует заголовку", "category": "content", "deterministic": False, "how": "VLM (вопрос 2)."},
    {"code": "one_sentence", "title": "Слайд пересказывается одним предложением", "category": "content", "deterministic": False, "how": "VLM (вопрос 3)."},
    {"code": "facts_supported", "title": "Цифры и факты есть в исходных материалах", "category": "content", "deterministic": False, "how": "VLM со сверкой с брифом (вопрос 4)."},
    {"code": "has_content", "title": "На слайде есть содержание", "category": "content", "deterministic": False, "how": "VLM (вопрос 5)."},
    {"code": "visuals_relevant", "title": "Картинки и иконки относятся к теме", "category": "content", "deterministic": False, "how": "VLM (вопрос 6)."},
    {"code": "no_garbage", "title": "Нет служебного мусора", "category": "content", "deterministic": False, "how": "VLM (вопрос 7)."},
    {"code": "typos", "title": "Текст без опечаток", "category": "content", "deterministic": False, "how": "VLM (вопрос 8)."},
    {"code": "deck_language", "title": "Вся колода на одном языке", "category": "content", "deterministic": False, "how": "LLM по тексту колоды (вопрос 9)."},
    {"code": "table_relevant", "title": "Строки таблицы и легенда работают на мысль", "category": "content", "deterministic": False, "how": "VLM (вопрос 10)."},
    {"code": "transition", "title": "Соседние слайды связаны по логике", "category": "content", "deterministic": False, "how": "LLM по тексту колоды (вопрос 11)."},
]

CATEGORIES = {"layout": "Вёрстка", "template": "Шаблон", "density": "Плотность", "integrity": "Целостность",
              "content": "Контент"}
